stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
    - src/data/data_ingestion.py
    outs:
    - data/raw/test.csv
    - data/raw/train.csv

  train_model:
    cmd: python src/model/train_model.py         # <-- fixed
    deps:
    - data/raw/train.csv
    - params.yaml
    - src/model/train_model.py                   # <-- fixed
    outs:
    - models/model.pkl

  evaluate_model:
    cmd: python src/features/evaluate_model.py
    deps:
    - data/raw/test.csv
    - models/model.pkl
    - src/features/evaluate_model.py
    outs:
    - evaluation/metrics.json

  predict:
    cmd: python src/predict/predict.py
    deps:
    - models/model.pkl
    - src/predict/predict.py
    outs:
    - prediction/output.csv
